# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c476f8a32027e6a33e2b40978bc4fd1fff44886fb8ecbe324e89dd20b06cbfcce8c03b9e1d4557d38c531177296fda21ee116e73b4314613ea0ac880a251b1e1

test:
  secret_key_base: 8824910d8632109ca611a9a22c8b54cec931b001cdd3fbc3d6bc908ecfda7af44b231ffe9530b8be5c74d4ee0d61f2a7512f91557492bc827d415593105f360c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
